/** \file
 *  This C header file was generated by $ANTLR version 3.1.3 Mar 17, 2009 19:23:44
 *
 *     -  From the grammar source file : Rho.g
 *     -                            On : 2009-11-25 13:46:25
 *     -                 for the lexer : RhoLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer RhoLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pRhoLexer, which is returned from a call to RhoLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pRhoLexer are  as follows:
 *
 *  -  void      pRhoLexer->T__44(pRhoLexer)
 *  -  void      pRhoLexer->T__45(pRhoLexer)
 *  -  void      pRhoLexer->T__46(pRhoLexer)
 *  -  void      pRhoLexer->T__47(pRhoLexer)
 *  -  void      pRhoLexer->T__48(pRhoLexer)
 *  -  void      pRhoLexer->T__49(pRhoLexer)
 *  -  void      pRhoLexer->T__50(pRhoLexer)
 *  -  void      pRhoLexer->T__51(pRhoLexer)
 *  -  void      pRhoLexer->T__52(pRhoLexer)
 *  -  void      pRhoLexer->T__53(pRhoLexer)
 *  -  void      pRhoLexer->T__54(pRhoLexer)
 *  -  void      pRhoLexer->T__55(pRhoLexer)
 *  -  void      pRhoLexer->T__56(pRhoLexer)
 *  -  void      pRhoLexer->T__57(pRhoLexer)
 *  -  void      pRhoLexer->T__58(pRhoLexer)
 *  -  void      pRhoLexer->T__59(pRhoLexer)
 *  -  void      pRhoLexer->T__60(pRhoLexer)
 *  -  void      pRhoLexer->T__61(pRhoLexer)
 *  -  void      pRhoLexer->T__62(pRhoLexer)
 *  -  void      pRhoLexer->T__63(pRhoLexer)
 *  -  void      pRhoLexer->T__64(pRhoLexer)
 *  -  void      pRhoLexer->T__65(pRhoLexer)
 *  -  void      pRhoLexer->T__66(pRhoLexer)
 *  -  void      pRhoLexer->T__67(pRhoLexer)
 *  -  void      pRhoLexer->T__68(pRhoLexer)
 *  -  void      pRhoLexer->T__69(pRhoLexer)
 *  -  void      pRhoLexer->T__70(pRhoLexer)
 *  -  void      pRhoLexer->T__71(pRhoLexer)
 *  -  void      pRhoLexer->T__72(pRhoLexer)
 *  -  void      pRhoLexer->T__73(pRhoLexer)
 *  -  void      pRhoLexer->T__74(pRhoLexer)
 *  -  void      pRhoLexer->T__75(pRhoLexer)
 *  -  void      pRhoLexer->T__76(pRhoLexer)
 *  -  void      pRhoLexer->T__77(pRhoLexer)
 *  -  void      pRhoLexer->T__78(pRhoLexer)
 *  -  void      pRhoLexer->T__79(pRhoLexer)
 *  -  void      pRhoLexer->T__80(pRhoLexer)
 *  -  void      pRhoLexer->T__81(pRhoLexer)
 *  -  void      pRhoLexer->T__82(pRhoLexer)
 *  -  void      pRhoLexer->T__83(pRhoLexer)
 *  -  void      pRhoLexer->T__84(pRhoLexer)
 *  -  void      pRhoLexer->T__85(pRhoLexer)
 *  -  void      pRhoLexer->T__86(pRhoLexer)
 *  -  void      pRhoLexer->T__87(pRhoLexer)
 *  -  void      pRhoLexer->T__88(pRhoLexer)
 *  -  void      pRhoLexer->T__89(pRhoLexer)
 *  -  void      pRhoLexer->T__90(pRhoLexer)
 *  -  void      pRhoLexer->T__91(pRhoLexer)
 *  -  void      pRhoLexer->T__92(pRhoLexer)
 *  -  void      pRhoLexer->T__93(pRhoLexer)
 *  -  void      pRhoLexer->T__94(pRhoLexer)
 *  -  void      pRhoLexer->T__95(pRhoLexer)
 *  -  void      pRhoLexer->T__96(pRhoLexer)
 *  -  void      pRhoLexer->T__97(pRhoLexer)
 *  -  void      pRhoLexer->T__98(pRhoLexer)
 *  -  void      pRhoLexer->T__99(pRhoLexer)
 *  -  void      pRhoLexer->T__100(pRhoLexer)
 *  -  void      pRhoLexer->T__101(pRhoLexer)
 *  -  void      pRhoLexer->T__102(pRhoLexer)
 *  -  void      pRhoLexer->T__103(pRhoLexer)
 *  -  void      pRhoLexer->T__104(pRhoLexer)
 *  -  void      pRhoLexer->T__105(pRhoLexer)
 *  -  void      pRhoLexer->T__106(pRhoLexer)
 *  -  void      pRhoLexer->T__107(pRhoLexer)
 *  -  void      pRhoLexer->T__108(pRhoLexer)
 *  -  void      pRhoLexer->T__109(pRhoLexer)
 *  -  void      pRhoLexer->T__110(pRhoLexer)
 *  -  void      pRhoLexer->T__111(pRhoLexer)
 *  -  void      pRhoLexer->T__112(pRhoLexer)
 *  -  void      pRhoLexer->T__113(pRhoLexer)
 *  -  void      pRhoLexer->T__114(pRhoLexer)
 *  -  void      pRhoLexer->T__115(pRhoLexer)
 *  -  void      pRhoLexer->T__116(pRhoLexer)
 *  -  void      pRhoLexer->T__117(pRhoLexer)
 *  -  void      pRhoLexer->T__118(pRhoLexer)
 *  -  void      pRhoLexer->T__119(pRhoLexer)
 *  -  void      pRhoLexer->T__120(pRhoLexer)
 *  -  void      pRhoLexer->T__121(pRhoLexer)
 *  -  void      pRhoLexer->T__122(pRhoLexer)
 *  -  void      pRhoLexer->T__123(pRhoLexer)
 *  -  void      pRhoLexer->T__124(pRhoLexer)
 *  -  void      pRhoLexer->T__125(pRhoLexer)
 *  -  void      pRhoLexer->T__126(pRhoLexer)
 *  -  void      pRhoLexer->T__127(pRhoLexer)
 *  -  void      pRhoLexer->T__128(pRhoLexer)
 *  -  void      pRhoLexer->T__129(pRhoLexer)
 *  -  void      pRhoLexer->T__130(pRhoLexer)
 *  -  void      pRhoLexer->T__131(pRhoLexer)
 *  -  void      pRhoLexer->T__132(pRhoLexer)
 *  -  void      pRhoLexer->T__133(pRhoLexer)
 *  -  void      pRhoLexer->T__134(pRhoLexer)
 *  -  void      pRhoLexer->T__135(pRhoLexer)
 *  -  void      pRhoLexer->T__136(pRhoLexer)
 *  -  void      pRhoLexer->T__137(pRhoLexer)
 *  -  void      pRhoLexer->T__138(pRhoLexer)
 *  -  void      pRhoLexer->T__139(pRhoLexer)
 *  -  void      pRhoLexer->HexLiteral(pRhoLexer)
 *  -  void      pRhoLexer->DecimalLiteral(pRhoLexer)
 *  -  void      pRhoLexer->OctalLiteral(pRhoLexer)
 *  -  void      pRhoLexer->HexDigit(pRhoLexer)
 *  -  void      pRhoLexer->IntegerTypeSuffix(pRhoLexer)
 *  -  void      pRhoLexer->FloatingPointLiteral(pRhoLexer)
 *  -  void      pRhoLexer->Exponent(pRhoLexer)
 *  -  void      pRhoLexer->FloatTypeSuffix(pRhoLexer)
 *  -  void      pRhoLexer->CharacterLiteral(pRhoLexer)
 *  -  void      pRhoLexer->StringLiteral(pRhoLexer)
 *  -  void      pRhoLexer->EscapeSequence(pRhoLexer)
 *  -  void      pRhoLexer->OctalEscape(pRhoLexer)
 *  -  void      pRhoLexer->UnicodeEscape(pRhoLexer)
 *  -  void      pRhoLexer->Identifier(pRhoLexer)
 *  -  void      pRhoLexer->QuotedIdentifier(pRhoLexer)
 *  -  void      pRhoLexer->Letter(pRhoLexer)
 *  -  void      pRhoLexer->JavaIDDigit(pRhoLexer)
 *  -  void      pRhoLexer->WS(pRhoLexer)
 *  -  void      pRhoLexer->COMMENT(pRhoLexer)
 *  -  void      pRhoLexer->LINE_COMMENT(pRhoLexer)
 *  -  void      pRhoLexer->Tokens(pRhoLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_RhoLexer_H
#define _RhoLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct RhoLexer_Ctx_struct RhoLexer, * pRhoLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for RhoLexer
 */
struct RhoLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mT__44)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__45)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__46)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__47)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__48)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__49)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__50)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__51)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__52)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__53)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__54)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__55)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__56)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__57)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__58)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__59)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__60)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__61)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__62)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__63)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__64)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__65)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__66)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__67)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__68)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__69)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__70)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__71)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__72)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__73)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__74)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__75)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__76)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__77)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__78)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__79)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__80)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__81)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__82)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__83)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__84)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__85)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__86)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__87)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__88)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__89)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__90)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__91)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__92)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__93)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__94)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__95)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__96)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__97)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__98)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__99)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__100)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__101)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__102)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__103)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__104)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__105)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__106)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__107)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__108)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__109)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__110)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__111)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__112)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__113)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__114)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__115)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__116)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__117)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__118)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__119)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__120)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__121)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__122)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__123)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__124)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__125)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__126)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__127)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__128)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__129)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__130)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__131)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__132)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__133)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__134)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__135)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__136)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__137)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__138)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mT__139)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mHexLiteral)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mDecimalLiteral)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mOctalLiteral)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mHexDigit)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mIntegerTypeSuffix)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mFloatingPointLiteral)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mExponent)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mFloatTypeSuffix)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mCharacterLiteral)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mStringLiteral)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mEscapeSequence)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mOctalEscape)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mUnicodeEscape)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mIdentifier)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mQuotedIdentifier)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mLetter)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mJavaIDDigit)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mWS)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mCOMMENT)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mLINE_COMMENT)	(struct RhoLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct RhoLexer_Ctx_struct * ctx);    const char * (*getGrammarFileName)();
    void	    (*free)   (struct RhoLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pRhoLexer RhoLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pRhoLexer RhoLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define FloatTypeSuffix      35
#define OctalLiteral      29
#define TRACE      23
#define EOF      -1
#define BREAK      22
#define Identifier      24
#define T__93      93
#define T__94      94
#define FIELD_ACCESS      5
#define T__91      91
#define T__92      92
#define T__90      90
#define COMMENT      42
#define T__99      99
#define T__98      98
#define T__97      97
#define T__96      96
#define T__95      95
#define T__139      139
#define T__138      138
#define T__137      137
#define T__136      136
#define T__80      80
#define T__81      81
#define QUOTED_RPN_SEQUENCE      13
#define T__82      82
#define T__83      83
#define LINE_COMMENT      43
#define IntegerTypeSuffix      33
#define ELSE      16
#define ARG_LIST      7
#define T__85      85
#define T__84      84
#define T__87      87
#define METHOD_CALL      4
#define ASSERT      17
#define T__86      86
#define T__89      89
#define T__88      88
#define IDENT_LIST      8
#define EMPTY      11
#define T__126      126
#define T__125      125
#define T__128      128
#define T__127      127
#define WS      41
#define T__71      71
#define T__72      72
#define T__129      129
#define T__70      70
#define FloatingPointLiteral      25
#define JavaIDDigit      40
#define T__76      76
#define FUNCTION_CALL      6
#define T__75      75
#define T__74      74
#define T__130      130
#define Letter      39
#define EscapeSequence      36
#define T__73      73
#define T__131      131
#define T__132      132
#define T__133      133
#define T__79      79
#define T__134      134
#define T__78      78
#define T__135      135
#define T__77      77
#define RPN_SEQUENCE      12
#define T__68      68
#define T__69      69
#define T__66      66
#define T__67      67
#define T__64      64
#define T__65      65
#define T__62      62
#define T__63      63
#define T__118      118
#define CharacterLiteral      26
#define T__119      119
#define T__116      116
#define T__117      117
#define T__114      114
#define T__115      115
#define T__124      124
#define T__123      123
#define Exponent      34
#define T__122      122
#define T__121      121
#define T__120      120
#define T__61      61
#define T__60      60
#define HexDigit      32
#define IF_ELSE      15
#define IF      14
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__107      107
#define T__108      108
#define T__109      109
#define T__103      103
#define T__59      59
#define T__104      104
#define T__105      105
#define T__106      106
#define T__111      111
#define T__110      110
#define T__113      113
#define T__112      112
#define EXISTS      18
#define LAMBDA      20
#define T__50      50
#define HexLiteral      28
#define T__46      46
#define T__47      47
#define T__44      44
#define T__45      45
#define T__48      48
#define T__49      49
#define CONTINUATION      19
#define T__102      102
#define T__101      101
#define T__100      100
#define DecimalLiteral      30
#define QuotedIdentifier      31
#define StringLiteral      27
#define DEBUG_BREAK      21
#define UnicodeEscape      37
#define BLOCK      10
#define ASSIGN      9
#define OctalEscape      38
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for RhoLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
